---
Name: search-list
---
SilverStripe\ORM\DataObject:
  extensions:
    - Marcz\Search\Extensions\IndexableFieldsExtension
    - Marcz\Search\Extensions\SearchDataListener
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Marcz\Search\Extensions\SearchContentExtension
Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Search\Extensions\SafeguardMember
Marcz\Search\Config:
  clients:
    - name: 'MySQL'
      write: false
      export: false
      class: 'Marcz\Search\Client\MySQLClient'
  example_client_config: |-
    <pre>
    Marcz\Search\Config:
      clients:
        - name: 'Swiftype'
          write: true
          export: 'json'
          class: 'Marcz\Swiftype\SwiftypeClient'
    </pre>
  example_index_config: |-
    <pre>
    Marcz\Search\Config:
      indices:
        - name: 'Pages'
          class: 'Page'
    </pre>
